mcp_servers:
  - id: documents
    script: mcp_server_2.py
    cwd: /app/mcp_servers
    description: "Load, search and extract within webpages, local PDFs or other documents. Web and document specialist"
  # - id: webbrowsing
  #   script: http://localhost:8100/sse  # SSE URL
  #   transport: sse
  #   description: "Full Browser Access (persistent)"
